apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client
  labels:
    app: client 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client  
  template:
    metadata:
      labels:
        app: client  
    spec:         
      containers:
      - name: client
        image: phelimb/bigsi-client
        ports:
          - containerPort: 80
