apiVersion: v1
kind: Service
metadata:
  name: bigsi-1-nginx-service
  labels:
    app: bigsi-1-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80  
    name: http  
  selector:
    app: bigsi-1-nginx
