SEQUENCE_QUERY_KEY = "seq"
THRESHOLD_KEY = "threshold"
SCORE_KEY = "score"
COMPLETED_BIGSI_QUERIES_COUNT_KEY = "completed_bigsi_queries"
TOTAL_BIGSI_QUERIES_COUNT_KEY = "total_bigsi_queries"
RESULTS_KEY = "results"
