apiVersion: v1
kind: Service
metadata:
  name: bigsi-aggregator
  labels:
    app: bigsi-aggregator
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001     
  selector:
    app: bigsi-aggregator