apiVersion: v1
data:
  config.yaml: |-
    h: 1
    k: 31
    m: 10000
    nproc: 1
    storage-engine: berkeleydb
    storage-config:
      filename: /data/all-microbial-bigsi-v03
      flag: "c" ## Change to 'r' for read-only access
kind: ConfigMap
metadata:
  name: bigsi-1-config

