kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-for-bigsi-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" ## Make sure this path exists on the local machine