apiVersion: v1
kind: Service
metadata:
  name: bigsi-nginx
  labels:
    app: bigsi-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80  
    name: http  
  selector:
    app: bigsi-nginx
